### ISSUE TITLE
Site problem

### ISSUE THREAD

**Issue by IvanIsak2000** [ZandercraftGames/ZandercraftGames#1]
Hello!
Your site don't work
![image](https://github.com/ZandercraftGames/ZandercraftGames/assets/79650307/21ceab84-92b0-4344-8f23-ad9237cbba99)

**Comment by ZandercraftGames** [comment]
Hey there! Apologies for this. It's a recurring issue with our new hosting solution that I have been trying to work out. I'll bring it back up in the morning.

**Comment by ZandercraftGames** [comment]
Hey @IvanIsak2000! I've just resolved the issue! Thank you so much for letting me know! 😄
